# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-15 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[(b'Medicamento', b'Medicamento'), (b'Alimentos', b'Alimentos'), (b'Ambiente', b'Ambiente'), (b'Otros', b'Otros')], max_length=12)),
                ('nombre_alergia', models.CharField(blank=True, max_length=20)),
                ('activo', models.CharField(blank=True, choices=[(b'Si', b'Si'), (b'No', b'No')], max_length=2)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesFamiliaresPatologicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.CharField(blank=True, max_length=50)),
                ('parentesco', models.CharField(blank=True, choices=[(b'Padre', b'Padre'), (b'Madre', b'Madre'), (b'Abuelos', b'Abuelos'), (b'Hermanos', b'Hermanos'), (b'Otros', b'Otros')], max_length=9)),
                ('antefamipatologicos', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AntecendentesPersonalesPatologicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('antepersopatologico', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evoluciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('notas', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inmunizaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta_vacunacion', models.CharField(blank=True, choices=[(b'Si', b'Si'), (b'No', b'No')], max_length=2)),
                ('nombre_vacuna', models.CharField(blank=True, max_length=20, null=True)),
                ('dosis_aplicadas', models.IntegerField(blank=True, null=True)),
                ('edad_aplicacion', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('tipo', models.CharField(blank=True, max_length=20)),
                ('dosis', models.CharField(blank=True, max_length=40)),
                ('frecuencia', models.CharField(blank=True, max_length=30)),
                ('via', models.CharField(blank=True, max_length=20)),
                ('nota', models.CharField(blank=True, max_length=40)),
                ('activo', models.CharField(blank=True, choices=[(b'Si', b'Si'), (b'No', b'No')], max_length=2)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoConsultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Otras_Ordenes_Terapeuticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('dieta', models.CharField(blank=True, max_length=60)),
                ('actividad_fisica', models.CharField(blank=True, max_length=30)),
                ('curas', models.CharField(blank=True, max_length=30)),
                ('oxigeno', models.CharField(blank=True, max_length=20)),
                ('fisioterapia_respiratoria', models.CharField(blank=True, max_length=20)),
                ('sondas_drenajes', models.CharField(blank=True, max_length=20)),
                ('estudios_lab_diagnostico', models.CharField(blank=True, max_length=60)),
                ('activo', models.CharField(blank=True, choices=[(b'Si', b'Si'), (b'No', b'No')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[(b'M', b'Masculino'), (b'F', b'Femenino')], max_length=9)),
                ('peso', models.FloatField(blank=True, max_length=5)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=26)),
                ('celular', models.CharField(blank=True, max_length=26)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('hora_ingreso', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.CharField(blank=True, max_length=30)),
                ('cedula_tutor', models.CharField(blank=True, max_length=30)),
                ('cedula_paciente', models.CharField(blank=True, max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='PadecimientoActuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('padecimiento', models.CharField(blank=True, max_length=100)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionesporSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('cabeza', models.CharField(blank=True, max_length=200)),
                ('ojos', models.CharField(blank=True, max_length=200)),
                ('oidos', models.CharField(blank=True, max_length=200)),
                ('nariz', models.CharField(blank=True, max_length=200)),
                ('boca', models.CharField(blank=True, max_length=200)),
                ('respiratorio', models.CharField(blank=True, max_length=200)),
                ('cardiovascular', models.CharField(blank=True, max_length=200)),
                ('gastrointestinal', models.CharField(blank=True, max_length=200)),
                ('urinario', models.CharField(blank=True, max_length=200)),
                ('neuromuscular', models.CharField(blank=True, max_length=200)),
                ('psiquismo', models.CharField(blank=True, max_length=200)),
                ('conducta', models.CharField(blank=True, max_length=200)),
                ('piel', models.CharField(blank=True, max_length=200)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Seguros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_seguro', models.CharField(blank=True, max_length=30)),
                ('numero_afiliado', models.CharField(blank=True, max_length=20)),
                ('activo', models.CharField(blank=True, choices=[(b'Si', b'Si'), (b'No', b'No')], max_length=2)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Signos_Vitales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('tension_arterial', models.CharField(blank=True, max_length=20)),
                ('frecuencia_cardiaca', models.CharField(blank=True, max_length=20)),
                ('frecuencia_respiratoria', models.CharField(blank=True, max_length=20)),
                ('temperatura', models.CharField(blank=True, max_length=20)),
                ('notas', models.CharField(blank=True, max_length=100)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(b'doctor', b'Doctor'), (b'nurse', b'Nurse'), (b'infero', b'Infero')], default=b'doctor', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='otras_ordenes_terapeuticas',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente'),
        ),
        migrations.AddField(
            model_name='motivoconsultas',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente'),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente'),
        ),
        migrations.AddField(
            model_name='inmunizaciones',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente'),
        ),
        migrations.AddField(
            model_name='evoluciones',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente'),
        ),
        migrations.AddField(
            model_name='antecendentespersonalespatologicos',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente'),
        ),
        migrations.AddField(
            model_name='antecedentesfamiliarespatologicos',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente'),
        ),
        migrations.AddField(
            model_name='alergias',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente'),
        ),
    ]
