# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alergias',
            name='activo',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='alergias',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Medicamento', 'Medicamento'), ('Alimentos', 'Alimentos'), ('Ambiente', 'Ambiente'), ('Otros', 'Otros')], max_length=12),
        ),
        migrations.AlterField(
            model_name='antecedentesfamiliarespatologicos',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Abuelos', 'Abuelos'), ('Hermanos', 'Hermanos'), ('Otros', 'Otros')], max_length=9),
        ),
        migrations.AlterField(
            model_name='inmunizaciones',
            name='tarjeta_vacunacion',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='activo',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='otras_ordenes_terapeuticas',
            name='activo',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula_tutor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tutor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seguros',
            name='activo',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('infero', 'Infero')], default='doctor', max_length=255),
        ),
    ]
